{
 "title": "Kubernetes / GPU Resources / Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Node Stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) by (node))",
     "legendFormat": "total"
    },
    {
     "expr": "count(sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}) by (node))",
     "legendFormat": "reserved"
    },
    {
     "expr": "sum(count(count(DCGM_FI_DEV_GPU_UTIL > 0) by (node)) by (node))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "GPU Node Stats (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}) by (node)) / sum(count(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) by (node)) * 100",
     "legendFormat": "reserved / total"
    },
    {
     "expr": "sum(count(count(DCGM_FI_DEV_GPU_UTIL > 0) by (node)) by (node)) / sum(count(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) by (node)) * 100",
     "legendFormat": "usage / total"
    }
   ]
  },
  {
   "title": "GPU Node Reserved (%)",
   "type": "marcusolsson-hexmap-panel",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "((count(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}) by (node) - 1) + (sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}) by (node)) or (count(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}) by (node) - 1)) / (sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}) by (node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Nodes Trends",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(count(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}) by (node))",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(count(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}) by (node))",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(count(count(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}) by (node)) by (node))",
     "legendFormat": "reserved"
    },
    {
     "expr": "sum(count(count(DCGM_FI_DEV_GPU_UTIL > 0) by (node)) by (node))",
     "legendFormat": "usage"
    }
   ]
  },
  { "title": "by Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "GPU Core Stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "reserved"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL > 0)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL > 0) / 100",
     "legendFormat": "util"
    }
   ]
  },
  {
   "title": "GPU Core Stats (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}) / sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "reserved / allocatable"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL > 0) / sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "usage / allocatable"
    },
    {
     "expr": "sum((DCGM_FI_DEV_GPU_UTIL > 0) / 100) / sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "util / allocatable"
    }
   ]
  },
  {
   "title": "GPU Cores Trends",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "reserved"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL > 0)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL > 0) / 100",
     "legendFormat": "util"
    }
   ]
  },
  { "title": "by ResourceQuota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "GPU ResourceQuota Stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"hard\"} > 0)",
     "legendFormat": "hard"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"used\"} > 0)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "GPU ResourceQuota Stats (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"used\"} > 0) / sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"hard\"} > 0) * 100",
     "legendFormat": "used / hard"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"hard\"} > 0) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "hard / allocatable"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"used\"} > 0) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "used / allocatable"
    }
   ]
  },
  {
   "title": "GPU ResourceQuota Trends",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"hard\"} > 0)",
     "legendFormat": "hard"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"used\"} > 0)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "GPU ResourceQuota Trends By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"hard\"} > 0) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "by Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "GPU Cores Reserved By Namespace Trends",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "GPU Cores Usage By Namespace Trends",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace!=\"\"} > 0) by (exported_namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "GPU Cores Util By Namespace Trends",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_namespace!=\"\"} > 0) by (exported_namespace) / 100",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "by Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "GPU Cores Reserved By Pod Trends",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}) by (pod) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GPU Cores Usage By Pod Trends",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace!=\"\"} > 0) by (exported_pod)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "GPU Cores Util By Pod Trends",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_namespace!=\"\"} > 0) by (exported_pod) / 100",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}