{
 "title": "Kubernetes / GPU Resources / Namespace",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"mlu-showroom-test\", resource=\"limits.nvidia.com/gpu\"}",
     "legendFormat": "quota"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\", namespace=\"$namespace\"})",
     "legendFormat": "reserved"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\"} > 0)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\"} > 0) / 100",
     "legendFormat": "util"
    }
   ]
  },
  {
   "title": "Trends",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"mlu-showroom-test\", resource=\"limits.nvidia.com/gpu\"}",
     "legendFormat": "quota"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\", namespace=\"$namespace\"})",
     "legendFormat": "reserved"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\"} > 0)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\"} > 0) / 100",
     "legendFormat": "util"
    }
   ]
  },
  { "title": "by Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GPU Cores Reserved By Pod Trends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\", namespace=\"$namespace\"}) by (pod) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GPU Cores Usage By Pod Trends",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\"} > 0) by (exported_pod)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "GPU Cores Util By Pod Trends",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\"} > 0) by (exported_pod) / 100",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "by Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Cores Reserved By Container Trends",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\", namespace=\"$namespace\"}) by (container) > 0",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "GPU Cores Usage By Container Trends",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\"} > 0) by (container)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "GPU Cores Util By Container Trends",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\"} > 0) by (container) / 100",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  }
 ]
}